const translateData = {
    am: {
        Product: "Ապրանք",
        Solutions: "Լուծումներ",
        Resources: "Ռեսուրսներ",
        Enterprise: "Ձեռնարկություն",
        Pricing: "Գնագոյացում",
        Contact: "Կապ",
        Login: "Մուտք",
        Sign: "Գրանցվել",
        box5_text_h1: "Նոր մտքերը այստեղ",
        box5_text1_p: "Miro-ն ձեր թիմի տեսողական հարթակն է՝ կապվելու, համագործակցելու և միասին ստեղծագործելու համար։",
        input2_enter: "Մուտքագրեք էլ․ հասցե",
        input2_sign: "Գրանցվել",
        box5_text5_p: "Համագործակցեք ձեր թիմի հետ րոպեների ընթացքում",
        box3_text_p: "Համագործակցեք առանց սահմանափակումների",
        of_p1: "Ընդմիշտ անվճար",
        we_p1: "Մեր անվճար պլանը ձեզ տրամադրում է անսահմանափակ թիմի անդամներ, 300+ մասնագետների կողմից պատրաստված ձևանմուշներ: Աշխատանքային էլ. փոստով գրանցվելը թույլ է տալիս ավելի արագ ներգրավել ձեր թիմին: Տեսեք մեր գնային պլանները՝ ավելի շատ հնարավորությունների համար:Our free plan gives you unlimited team members, 3 boards, and 300+ expert-made templates. Signing up with your work email lets you bring in your team faster. See our pricing plans for more features.",
        of_p2: "Հեշտ ինտեգրացիաներ",
        we_p2: "Miro has 100+ powerful integrations with tools you already use like G Suite,Slack, and Jira, so your workflow is seamless. View the full list in our Marketplace .",
        of_p3: "Անվտանգությունն առաջին տեղում է",
        we_p3: "Մենք Ձեր տվյալներին վերաբերվում ենք այնպես, ինչպես Դուք կանեիք՝ առավելագույն խնամքով։ Մենք հետևում ենք ոլորտի առաջատար անվտանգության չափանիշներին և Ձեզ տրամադրում ենք գործիքներ մտավոր սեփականությունը պաշտպանելու համար։ Իմացեք ավելին մեր վստահության կենտրոնում։",
        work: "Աշխատեք միասին",
        box55_text1: "Գրասենյակում, հեռակա կամ երկուսի համադրությամբ, Miro-ի միջոցով ձեր թիմը կարող է կապ հաստատել, համագործակցել և համատեղ ստեղծագործել մեկ տարածքում՝ անկախ նրանից, թե որտեղ եք գտնվում։",
        section6_text: "Ստեղծված է ձեր աշխատանքի ձևի համար",
        Brainstorming: "Մտքերի փոթորիկ",
        Diagramming: "Դիագրամների կազմում",
        Meetings: "Հանդիպումներ և սեմինարներ",
        Scrum: "Scrum միջոցառումներ",
        Mapping: "Քարտեզագրում",
        Research: "Հետազոտություն",
        Strategic: "Ռազմավարական պլանավորում",
        Brainstorming1: "Փոթորիկ",
        Unleash: "Ազատագրե՛ք ստեղծագործական գաղափարները և զարգացրե՛ք դրանք կպչուն թղթերի, պատկերների, մտքի քարտեզների, տեսանյութերի, նկարչական հնարավորությունների օգնությամբ՝ ցանկը շարունակվում է։",
        Design: "UX և դիզայն",
        Marketing: "Մարքեթինգ",
        Product: "Արտադրանքի կառավարում",
        Engineering: "Ճարտարագիտություն",
        Consultants: "Խորհրդատուներ",
        Agile: "Agile մարզիչներ",
        Sales: "Վաճառքներ",
        box3_text_text: "Սիրված է աշխարհի լավագույն թիմերի կողմից",
        box3_text_text1: "Տեսնել բոլորինը",
        when: "Miro-ն ապացուցեց, որ կատարյալ գործիք է հեռավար աշխատանքի ընթացքում համագործակցության, սպիտակ գրատախտակի և հետահայաց ներկայացումների համար",
        Roxanne: "Ռոքսան Մուստաֆա",
        Design: "VMware-ի դիզայնի խմբի ղեկավար»",
        Miro: "“Miro-ն օգնում է լուծել արտադրանքի դիզայնի հիմնական բացթողումներից մեկը՝ ինչպես կառավարել արտադրանքի դիզայներների առաջադրանքները, որոնց նախագծերը գտնվում են տարբեր գործիքներում։”",
        Jane: "Ջեյն Էշլի",
        head: "Դիզայնի ղեկավար DocuSign-ում",
        as: "“Miro-ն օգտագործելիս մենք անցանք նորարարության, և հիմա մենք ունենք մի գործիք, որը մեր գործունեության հիմքում է և կշարունակի ընդլայնվել ապագայում։”",
        laura:"Լորա Բեյրդ",
        at:"Frog-ի դիզայնի տնօրենի օգնական",
        Product1: "Արտադրանք",
        online:"Առցանց",
        app:"Հավելվածներ",
        Templates:"Շաբլոններ",
        Miroverse:"Միրովերս",
        Developer:"Miro հարթակ",
        Devices:"Miro սարքերի համար",
        Security:"Անվտանգություն",
        Accessibility:"Հասանելիություն",
        Changelog:"Փոփոխությունների ցանկ",
        Solutions:"Լուծումներ",
        Meetings:"Հանդիպումներ",
        Brainstorming:"Գաղափարներ",
        Agile:"Աշխատանքային հոսքեր",
        Community:"Համայնքային բլոգ",
        Strategy:"Ռազմավարություն",
        Mind:"Քարտեզ",
        Online:"Առցանց ստիկերներ",
        Flowchart:"Բլոգ",
        Wireframing:"Wireframe մոդելավորում",

        Resource:"Ռեսուրս",
        Academy:"Miro ակադեմիա",
        Blog:"Բլոգ",
        Status:"Կարգավիճակ",
        Community:"Miro համայնք",
        Professional:"Miro ​​ցանց",
        Directory:"Miro Մասնագետներ",
        Events:"Miro Միջոցառումներ",

        Company:"Ընկերություն",
        About:"Մեր մասին",
        Careers:"Կարիերա",
        News:"Miro-ն լուրերում",
        Customer:"Հաճախորդների պատմություններ",

        Plans:"Պլաններ",
        Pricing:"Գներ",
        Business:"Բիզնես",
        Enterprise:"Ձեռնարկություն",
        Consultants:"Խորհրդատուներ",
        Pricing:"Գներ",
        Education:"Կրթություն",
        Startups:"Ստարտափներ",
        NPOs:"ՈՍՀԿ",

    },
    ru: {
        Product: "Продукт",
        Solutions: "Решение",
        Resources: "Ресурсы",
        Enterprise: "Предприятие",
        Pricing: "Ценообразование",
        Contact: "Контакт",
        Login: "Авторизоваться",
        Sign: "Зарегистрироваться",
        box5_text_h1: "Новые идеи здесь.",
        box5_text1_p: "Miro — это визуальная платформа для вашей команды, позволяющая общаться, сотрудничать и творить вместе.",
        input2_enter: "Введите адрес электронной почты",
        input2_sign: "Зарегистрироваться",
        box5_text5_p: "Взаимодействуйте со своей командой за считанные минуты",
        box3_text_p: "Сотрудничайте без ограничений",
        of_p1: "Всегда бесплатно",
        we_p1: "Наш бесплатный тарифный план включает неограниченное количество участников команды, 3 доски и более 300 шаблонов, созданных экспертами. Регистрация с использованием рабочего адреса электронной почты позволит вам быстрее подключить команду. Ознакомьтесь с нашими тарифными планами, чтобы узнать о других функциях.",
        of_p2: "Простая интеграция",
        we_p2: "«Miro предлагает более 100 мощных интеграций с инструментами, которые вы уже используете, такими как G Suite, Slack и Jira, что обеспечивает бесперебойность рабочего процесса. Полный список смотрите в нашем магазине приложений».",
        of_p3: "Безопасность прежде всего",
        we_p3: "Мы обращаемся с вашими данными так же, как и вы, — с максимальной заботой. Мы соблюдаем ведущие в отрасли стандарты безопасности и предоставляем вам инструменты для защиты интеллектуальной собственности. Узнайте больше в нашем Центре доверия.",
        work: "Работайте вместе",
        box55_text1: "Работая в офисе, удаленно или в сочетании этих двух вариантов, с помощью Miro ваша команда сможет общаться, сотрудничать и совместно творить в одном пространстве, где бы вы ни находились.",
        section6_text: "Создано с учетом вашего стиля работы",
        Brainstorming: "Мозговой штурм",
        Diagramming: "Диаграммы",
        Meetings: "Встречи и семинары",
        Scrum: "События Scrum",
        Mapping: "Картографирование",
        Research: "Исследования и дизайн",
        Strategic: "Стратегическое планирование",
        Brainstorming1: "Штурм",
        Unleash: "Раскройте свой потенциал: «Дайте волю творческим идеям и развивайте их с помощью стикеров, изображений, интеллект-карт, видео, возможностей рисования — и этот список можно продолжать».",
        Design: "UX и дизайн",
        Marketing: "Маркетинг",
        Product: "Управление продуктом",
        Engineering: "Инженерное дело",
        Consultants: "Консультанты",
        Agile: "Agile-тренеры",
        Sales: "Продажи",
        box3_text_text: "Любимец лучших команд мира",
        box3_text_text1: "Истории клиентов",
        when: "Когда началась пандемия, те из нас, кто ценит личное сотрудничество, беспокоились, что пострадают наша креативность и продуктивность. Miro оказался идеальным инструментом для совместной работы, работы с доской и проведения ретроспектив в режиме удалённой работы",
        Roxanne: "Роксанна Мустафа",
        Design: "Руководитель группы дизайна в VMware",
        Miro: "“Miro помогает решить один из основных пробелов в проектировании продуктов: как управлять задачами между дизайнерами продуктов, чьи проекты реализуются в разных инструментах.",
        Jane: "Джейн Эшли",
        head: "Руководитель отдела дизайна в DocuSign",
        as: "Используя Miro, мы перешли от скептицизма к вере, а затем к инновациям, и теперь у нас есть инструмент, который лежит в основе всего, что мы делаем, и будет продолжать развиваться в будущем.",
        laura:"Лора Бэрд",
        at:"Заместитель директора по дизайну в Frog",
        Product1:"Продукты",
        online:"Онлайн-доска",
        app:"Приложения и интеграции",
        Templates:"Шаблоны",
        Miroverse:"Мировселенной",
        Developer:"Платформа Miro",
        Devices:"Miro для устройств",
        Security:"Безопасность",
        Accessibility:"Доступность",
        Changelog:"Журнал изменений",
        Solutions:"Решения",
        Meetings:"Встречи и семинары",
        Brainstorming:"Генерация идей",
        Agile:"Рабочие процессы",
        Community:"Блог сообщества",
        Strategy:"Стратегия",
        Mind:"Карта",
        Online:"Онлайн-стикеры",
        Flowchart:"Блок",
        Wireframing:"Моделирование",

        Resource:"Ресурсы",
        Academy:"Академия Miro",
        Blog:"Блог",
        Status:"Статус",
        Community:"Miro Сообщество",
        Professional:"Miro Сеть",
        Directory:"Miro Справочник ",
        Events:"Miro События",

        Company:"Компания",
        About:"О нас",
        Careers:"Карьера",
        News:"Миро в новостях",
        Customer:"Истории клиентов",

        Plans:"Планы",
        Pricing:"Цены",
        Business:"Бизнес",
        Enterprise:"Предприятие",
        Consultants:"Консультанты",
        Pricing:"Цены",
        Education:"Образование",
        Startups:"Стартапы",
        NPOs:"НКО",
    },
    en: {
        Product: "Product",
        Solutions: "Solutions",
        Resources: "Resources",
        Enterprise: "Enterprise",
        Pricing: "Pricing",
        Contact: "Contact Sales",
        Login: "Login",
        Sign: "Sign up free",
        box5_text_h1: "Take ideas from better to best",
        box5_text1_p: "Miro is your team's visual platform to connect, collaborate, and create — together.",
        input2_enter: "Enter your work email",
        input2_sign: "Sign up free",
        box5_text5_p: "Collaborate with your team within minutes",
        box3_text_p: "Collaborate without constraints",
        of_p1: "Free forever",
        we_p1: "Our free plan gives you unlimited team members, 3 boards, and 300+ expert-made templates. Signing up with your work email lets you bring in your team faster. See our pricing plans for more features",
        of_p2: "Easy integrations",
        we_p2: "Miro has 100+ powerful integrations with tools you already use like G Suite,Slack, and Jira, so your workflow is seamless. View the full list in our Marketplace .",
        of_p3: "Security first",
        we_p3: "We treat your data like you would — with the utmost care. We follow industry-leading security standards and give you tools to protect intellectual property. Learn more at our Trust Center .",
        work: " Work together, wherever you work",
        box55_text1: "In the office, remote, or a mix of the two, with Miro, your team can connect, collaborate, and co-create in one space no matter where you are.",
        section6_text: "Built for the way you work",
        Brainstorming: "Brainstorming",
        Diagramming: "Diagramming",
        Meetings: "Meetings & Workshops",
        Scrum: "Scrum Events",
        Mapping: "Mapping",
        Research: "Research & Design",
        Strategic: "Strategic Planning",
        Brainstorming1: "Brainstorming",
        Unleash: "Unleash creative ideas and build on them with the help of sticky notes, images,mind maps, videos, drawing capabilities — the list goes on.",
        Design: "UX & Design ",
        Marketing: "Marketing",
        Product: "Product Management ",
        Engineering: "Engineering",
        Consultants: "Consultants",
        Agile: "Agile Coaches",
        Sales: "Sales",
        box3_text_text: "Loved by the world's best teams",
        box3_text_text1: "See all customer stories",
        when: "“When the pandemic hit, those of us who thrive on in-person collaboration were worried that our creativity and productivity would suffer. Miro was the perfect tool to help us with collaboration, whiteboarding, and retrospectives while remote.”",
        Roxanne: "Roxanne Mustafa",
        Design: "Design Team Lead at VMware",
        Miro: "“Miro helps solve one of the major gaps in product design: how to manage tasks across product designers whose projects are in different tools.”",
        Jane: "Jane Ashley",
        head: "Head of Design at DocuSign",
        as: "“As we used Miro we moved from skepticism to belief to innovation, and now we have a tool that’s at the core of what we do and will continue to extend into the future.”",
        laura:"Laura Baird",
        at:"Associate Design Director at frog",
        Product1:"Product",
        online:"Online whiteboard",
        app:"Apps & Integrations",
        Templates:"Templates",
        Miroverse:"Miroverse",
        Developer:"Miro Developer Platform",
        Devices:"Miro for Devices",
        Security:"Security & Compliance",
        Accessibility:"Accessibility",
        Changelog:"Changelog",
        Solutions:"Solutions",
        Meetings:"Meetings and Workshops",
        Brainstorming:"Brainstorming & Ideation",
        Agile:"Agile Workflows",
        Community:"Community Blog",
        Strategy:"Strategy & Planning",
        Mind:"Mind Map",
        Online:"Online Sticky Notes",
        Flowchart:"Flowchart",
        Wireframing:"Wireframing",

        Resource:"Resource",
        Academy:"Miro Academy",
        Blog:"Blog",
        Status:"Status",
        Community:"Miro Communit",
        Professional:"Miro Professional Network",
        Directory:"Miro Experts Directory",
        Events:"Miro Events",

        Company:"Company",
        About:"About us",
        Careers:"Careers",
        News:">Miro in the News",
        Customer:"Customer Stories",

        Plans:"Plans and Pricing",
        Pricing:"Pricing",
        Business:"Business",
        Enterprise:"Enterprise",
        Consultants:"Consultants",
        Pricing:"Pricing",
        Education:"Education",
        Startups:"Startups",
        NPOs:"NPOs",


    }
}

const laguagesSelect = document.getElementById("laguagesSelect")
const elements = document.querySelectorAll("[data-key]")


laguagesSelect.onchange = () => {
    let selectedLanguage = laguagesSelect.value
    localStorage.setItem("language", selectedLanguage)
    translateElements()
}

function translateElements() {
    let language = localStorage.getItem("language")
    document.documentElement.lang = language

    elements.forEach(element => {
        let key = element.getAttribute("data-key")
        element.textContent = translateData[language][key]
    })

}

window.addEventListener("load", function () {
    translateElements()
    laguagesSelect.value = localStorage.getItem("language")
})